### ISSUE TITLE
Tutorial controller Pages and file_exists() case sensitivity

### ISSUE THREAD

**Issue by dafriend** [bcit-ci/CodeIgniter4#1030]
The PHP function ```file_exists()``` follows OS handling of case sensitivity. In the tutorial the view file is to be named  using uppercase first - **Home.php** . Then the tutorial code uses a  conditional in  ```Pages::view```.

```
public function view($page = 'home')
{
	if ( ! file_exists(APPPATH.'Views/Pages/'.$page.'.php'))
	{
		// Whoops, we don't have a page for that!
		throw new \CodeIgniter\PageNotFoundException($page);
	}
```
When the url ```http://example.com//index.php/pages/view``` is requested, and the OS is case-sensitive, the above conditional results in the exception being thrown.  "home.php" is not a file that exists in a case-sensitve OS.

In the context of the tutorial, there are many ways to fix this issue. Any one of these will work

- Change the file name to "home.php" (lower case first)
- Redefine the method to ```public function view($page = 'Home');```
- Make sure ```$page``` will match the designed file name, i.e. ```$page = ucfirst($page);```
- Require that view files use the UC first naming convention, which doesn't really eliminate the need for  ```$page = ucfirst($page);``` 

Seems to me this problem begs the question about a file naming convention for view files. There is nothing in the CI4 [PHP Style Coding Guide](https://bcit-ci.github.io/CodeIgniter4/contributing/styleguide.html) regarding naming of "view" files. Should there be? Or does the framework need a helper that looks twice (UC-first and LC-first) for view file names? Or does the documentation need to point out case-sensitivity as a potential issue for developers? All of the above?

I'm happy to contribute a PR to the tutorial code and/or documentation if given some direction on what needs to be done.

**Comment by jim-parry** [comment]
Hmmm - the tutorial does ask that the user create a file application/views/pages/home.php (https://www.codeigniter.com/user_guide/tutorial/static_pages.html#adding-logic-to-the-controller). Note the case!

The tutorial has other issues, with potentially confusing method names, but I don't see the problem you suggest is there.

View filenames do not have a convention, on purpose - they can be whatever case you want, so long as you ask for them the same way. We do not want to go anywhere near trying to guess a developer's intent. UCfirst then LCfirst leads to UCsecond and LCfirstUCsecond ... and so on.

Am I missing something?

**Comment by gabpnr** [comment]
jim, you're wrong, in the CI4 userguide : https://bcit-ci.github.io/CodeIgniter4/tutorial/static_pages.html?adding-logic-to-the-controller
"In that directory, create two files named Home.php and About.php. "
So, then, the following example does not work, as he says and probably avoid confusion.

I always saw views files in lowercase (since CI2). I think that's the way to do it ... maybe the CI4 userguide should always has views filenames in lowercase.

**Comment by dafriend** [comment]
With regard to the tutorial, I think ```Pages::view()``` would be better off without the ```file_exists()``` check. The existence of the file will eventually to be checked by ```View::render()```  which will throw an exception if the file isn't found. Shouldn't that be enough of a heads-up during the development phase? 

Barring some other fix, the documentation should probably add some admonishments regarding "precisely matching view file names in your code". As an example, the tutorial could show what happens when you don't (for those with case-sensitve systems).

**Comment by lonnieezell** [comment]
I've committed a fix for the user guide. Thanks for bringing it to our attention! 

As for throwing the error inside of `Pages::view()` - the developer should be encouraged to throw a `PageNotFoundException` there still. The exception thrown within the the View class is intended for the developer and doesn't work well in production. Since the `Pages::view` method is intended to display any page that a view exists for, it should display a 404 - Page Not Found if it can't actually be found.
