### ISSUE TITLE
Routing for "cli" actions.

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#1166]
I am trying to implement some useful funcs for admin panel which are accessible from console. 
For. ex. as long as in my config (Routes.php) is: 
`$routes->cli('passwd', 'App\Controllers\Admin\Tools::passwd');`
command like:
`../public$ php -q index.php passwd `
works great.

But when I am trying to make an hierarchy like:
`$routes->cli('cli-admin/passwd', 'App\Controllers\Admin\Tools::passwd');`
or:
```
$routes->group(
    'cli-admin',
    function($routes)
    {
$routes->cli('passwd', 'App\Controllers\Admin\Tools::passwd');
    }
);

```
command like
`../public$ php -q index.php cli-admin passwd `

returns HTML of my route defined for "/"  and all types of escaping "-" gives no change. If there is no "-" in any segment it works ok.

**Comment by lonnieezell** [comment]
That's a limitation of command lines that I don't believe we can do much about, since it has to do with parsing flags, etc. 

However - there's something better to use for that: [Console commands](https://bcit-ci.github.io/CodeIgniter4/general/cli_commands.html). New to CI4, they allow you to do exactly what you're trying to do here.

**Comment by nowackipawel** [comment]
thx
