### ISSUE TITLE
HTTP/Request.php Error

### ISSUE THREAD

**Issue by InsiteFX** [bcit-ci/CodeIgniter4#132]
HTTP/Request.php Error

Is throwing an error in phpStorm 2016.1.2 on Line: 174

sscanf($proxy_ips[$i], '%[^/]/%d', $netaddr, $masklen);

$masklen has not been defined. Could be phpStorm just wanted to let you know.

If you define it the error goes away.

**Comment by lonnieezell** [comment]
Yeah, I've seen that one, too. It's annoying. :) The variable is created and populated by the sscanf method so I hadn't bothered changing it yet, since it's a language feature and seems to be just a PHPStorm thing. Though, to be fair, that method is one that I pretty much copy/pasted from CI3, so haven't looked too closely at it.

**Comment by InsiteFX** [comment]
I only see these errors when I view the source files, the application does run fine so it is probably PhpStorm causing it.
