### ISSUE TITLE
No listFields() method in Postgre connection

### ISSUE THREAD

**Issue by Portaflex** [bcit-ci/CodeIgniter4#151]
Error: Call to undefined method CodeIgniter\Database\Postgre\Connection::listFields()

At BASEPATH/Database/BaseConnection.php at line 1263, method fieldExist() calls listFields() wich is absent

```/**
	 * Determine if a particular field exists
	 *
	 * @param	string
	 * @param	string
	 * @return	bool
	 */
	public function fieldExists($fieldName, $tableName)
	{
		return in_array($fieldName, $this->listFields($tableName));
	}
```

**Comment by dsalac** [comment]
I found the way as follows:

1. Change method fieldExists() to call method _listColumns() instead of listFields()
```
public function fieldExists($fieldName, $tableName)
	{
		return in_array($fieldName, $this->_listColumns($tableName));
	}
```
2. Abstract method _listColumns() on BaseConnection.php has to return an array, not a string
```
abstract protected function _listColumns(string $table = '');
```
3. Method _listColumns() in /Postgre/Connection.php (line 257) has to return the query row array
```
protected function _listColumns(string $table = '')
	{
		$sql = 'SELECT "column_name"
			FROM "information_schema"."columns"
			WHERE LOWER("table_name") = '
			.$this->escape(strtolower($table));
		return $this->query($sql)->getRowArray();
	}
```
Little changes ... ¡big joy!
