### ISSUE TITLE
Controller return output instead of echo view

### ISSUE THREAD

**Issue by timothymarois** [bcit-ci/CodeIgniter4#179]
```
public function index()
{
    return view('welcome_message');
}
```

instead of `echo view('welcome_message');`

To have the controller "return" it's output would go with modern standards. Using echo within controller is bad practice, though the CI4 isn't complete and it was just an example with the Home.php (welcome), however I wanted to make a note of that. 

Returning a view should display that view, returning an "array" should automatically encode that into JSON output (Like Laravel). A controller acts as an API, so should make predictions to how it would be used and save work for developers. Of course there could be configurations to change any built-in functionality. Unless I am working on php and html mixed pages, using `echo` in classes is worrisome. 

Not a major issue, just a request to clean up functionality. (of course echo would always be allowed based on php, but a return would seem cleaner on the output, and prevent other code below from loaded if I've already returned my view)

**Comment by lonnieezell** [comment]
Thanks for the idea, and I'll definitely think on it and let the other team members get their opinions in, but here's my initial thoughts. 

What happens if you want to use more than one view, as has traditionally been done in CodeIgniter? What happens if you've decided to use it HMVC style, like so many do, and actually want an array returned? Then we have to have more code to undo what the default is. You've got to remember, too, that Laravel's view() method returns an object that can be typecast, not a string. 

I can understand your thinking here. Heck, I work with Laravel at my day job currently, and there are some things that would definitely be nice, but I have to remind myself constantly of CodeIgniter's roots. At it's core, CI is a on the explicit side of operations, while Laravel is very implicit in almost everything. Both methods have their pros and cons, but my gut instinct here is to NOT create implicit return handlers, instead creating methods to assist the user in making the type of output they desire. Before Milestone 2 ships, we'll definitely be taking a look at the whole process of working with or building API's, primarily--but not solely--dealing with JSON.

**Comment by timothymarois** [comment]
@lonnieezell Valid Points. My thinking on multiple views, would not be to echo them in order of display, but rather put views into variables and/or display them directly within other views. Or really, why not add the ability to have a "return" to view on controller; because what other actions could you use with a controller return? You wouldn't call controllers within controllers (at least not in my understanding of conceptual MVC), users can get the same use out of echo, and a return just adds built-in output. But I guess that is my thinking to how I use laravel or CI in web app development. I normally wouldn't do echo view, and then echo view again elsewhere because that creates a procedural like output. But again, maybe there are examples of use I'm not as familiar with.

**Comment by jim-parry** [comment]
What I see ... am I wrong?

The CI3 view echoed unless the third parameter was true. More precisely, the Loader's view method either added the view file to the controller's overall output buffer or it returned it.

I see that the View::render() also has a third (boolean) parameter, but its purpose is whether to clear the incoming view parameters. The render method currently returns the output, period.

It strikes me that the current View is more flexible than CI3's, in that you can choose whether to echo it immediately, append it to an overall output buffer (though you have to define it), or store it for later use as a view fragment.

Is the similarity in signatures clouding the issue?

**Comment by lonnieezell** [comment]
No, I think he's just used to working in the "newer", Laravel-esque, manner. I think we could make the CodeIgniter class catch the output and, if it's a string, add it to the Response's body. That would allow both methodologies to work, and returning does feel a little more proper though, in actuality, the echo is just being caught by the output buffer and added to the response, anyway.

**Comment by jim-parry** [comment]
fwiw, I believe that a controller's job is to respond to an HTTP message.
To me, it is not logical that a controller return anything, castable or not.
Following the Java servlet approach, the controller would write to the HTTP response object's output stream as part of fullfilling its obligations.
The approach that I see in CI4 appears to be a hybrid, with a response object that expects its "body" property to be set externally.

**Comment by lonnieezell** [comment]
I think we all agree that a controller's job is to respond to that HTTP request - the devil is just in the details. :) 

If you think that the request leads to the controller's method, then it makes some sense that it returns it's output, just like any other function. 

Honestly, both ways make sense to me, which is why I don't have a problem type-hinting a return value. The only issue I could see there is people might want to continue going down that road, which I don't think is something I really want us to do.

**Comment by jim-parry** [comment]
I misworded my last message ... should have been "handle an HTTP message", ensuring that a response gets sent to the user agent, but not implying any return value :-/
