### ISSUE TITLE
Cache/Session fallback to predis/predis composer package if phpredis not available

### ISSUE THREAD

**Issue by gdhnz** [bcit-ci/CodeIgniter4#192]
It would be useful if there was a fallback to the predis/predis composer package if the phpredis extension is not available.

There're instances where I've got access to a redis server but due to things outside my control, I can't get the phpredis extension installed on the server.

**Comment by lonnieezell** [comment]
It looks like it might get a little hairy to combine them into a single handler, since Predis they don't seem to have the same interface from what I can see. 

I wouldn't mind one of these as an additional driver, though, so if you wanted to put one together in a PR that would be great. My experience with Redis in general is rather limited, and, while I'm sure I could get up to speed, it sounds like you're more intimately familiar with it already.

**Comment by gdhnz** [comment]
I've got a tentative driver done for predis.  The only differences are how to connect and the predis calls to redis are all lowercase rather than the phpredis mixed-case.

Should I add a $predis entry in application/Config/Cache.php with some defaults or would you rather I extend the CacheFactory.php so as to reuse the existing $redis config?

**Comment by lonnieezell** [comment]
Thanks for the pull request! I've reviewed it and just have one comment that I made over there. 

I'll close this Issue, though, since you've basically got it.

On future PR's will likely ask for tests, but since the Session libraries don't have any tests at the moment, that wouldn't be very fair of me. :)

**Comment by gdhnz** [comment]
At the moment, my pull request only provides a cache driver.

I've got a session driver ready but it does it's own set_session_handler. So most of the read, write methods etc don't actually get used.
