### ISSUE TITLE
Missing {memory_usage} ?

### ISSUE THREAD

**Issue by mixinix** [bcit-ci/CodeIgniter4#197]
I think that is simple benchmarking (with parser) with {elapsed_time} as we love in CodeIgniter ver <= 3.

**Comment by lonnieezell** [comment]
I implemented that real quick, since I'd enjoyed that in the past, also, and remembered why I took it out. First off - it shows up in the Debug Toolbar already, so it didn't really seem necessary. Second, it shows a different memory usage than what is in the Toolbar, simply because the toolbar classes haven't been loaded when the on-page replacement is calculated. 

Seems that might get confusing for users?

**Comment by lonnieezell** [comment]
@mixinix Thoughts?

**Comment by mixinix** [comment]
give up.... :)

**Comment by h4km** [comment]
what can I do for this?

**Comment by lonnieezell** [comment]
@h4km Don't think there's anything to do here. Memory is already included on debug bar, and the difference in memory usage would be confusing. Not implementing. Thanks though!
