### ISSUE TITLE
A suggestion for debug exceptions layout

### ISSUE THREAD

**Issue by mixinix** [bcit-ci/CodeIgniter4#295]
I think using modal with maximum CSS **z-index** can fix broken the layout like this:
[CodeIgniter4 sample](https://drive.google.com/file/d/0ByljD7gaC0xfWm45X0Z1a0UxY2M/view?usp=sharing)

And this is an example with bootstrap I made:
[Custom sample](https://drive.google.com/file/d/0ByljD7gaC0xfY3pfT0pqSTVYdE0/view?usp=sharing)

or one button for show and hide the error screen.

Just a little idea.

Thank you Sir, for your fast response!

**Comment by lonnieezell** [comment]
The styles used should be constrained to the page itself, though we might be able to tie that down a little more. That said, I've never seen the layout do that before. We can't necessarily do modals because every front-end framework is different, and we don't need to pull an entire framework in just to handle a debug page.

Do you have any idea what was causing the layout issue to begin with?

**Comment by mixinix** [comment]
I don't have, because an error layout (segment) is different with debug bar.
An error layout maight be wrapped by other (parent) tag/layout element.

```
<pre><!-- or other element with style -->
    <div id="errorDiv">error layout</div>
</pre>
```

The advantages of using modal, we can find or showing en error slightest that not detected by user/developer.

**Comment by lonnieezell** [comment]
Closing this one for now. While modals are definitely an interesting solution, I can see them being more problematic as people start to integrate into their projects. 

I have made changes in the past to help with this, though, including clearing the output buffer when an exception happens and a couple of other small tweaks. I think we're good here. 

Thanks.
