### ISSUE TITLE
session class: inconsistency on get() between document and code

### ISSUE THREAD

**Issue by noldor** [bcit-ci/CodeIgniter4#330]
on the document:
https://github.com/bcit-ci/CodeIgniter4/blob/develop/user_guide_src/source/libraries/sessions.rst

> .. important:: The ``get()`` method WILL return flashdata items.

and

> .. important:: The ``get()`` method will NOT return tempdata items.

on the source code:
https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Session/Session.php#L432

```
		$userdata = [];
		$_exclude = array_merge(
				['__ci_vars'], $this->getFlashKeys(), $this->getTempKeys()
		);


		foreach (array_keys($_SESSION) as $key)
		{
			if (! in_array($key, $_exclude, true))
			{
				$userdata[$key] = $_SESSION[$key];
			}
		}
		return $userdata;
```

There are any wrong. Perhaps, the first.

**Comment by lonnieezell** [comment]
Good catch. It turns out that when retrieving either flashdata or tempdata with a key in the the `get()` method, it WILL return it since it's just pulling the value directly from $_SESSION. However, if you're using `get()` to retrieve ALL userdata from the session, it won't include them. A little confusing, but I've clarified the docs on this point.

**Comment by noldor** [comment]
All right. Thank you for fixing it.
