### ISSUE TITLE
Request setBody not working

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#332]
Hi,

		$this->response->setHeader('Content-type', 'application/json');
		$this->response->setStatusCode(200)
		               ->setBody(json_encode($json));

Only variables should be passed by reference // ->setBody(json_encode($json));

Working;
$this->response->setHeader('Content-type', 'application/json');
echo json_encode($json);

Message Class not extended, HTTP\Response.

**Comment by lonnieezell** [comment]
> Message Class not extended, HTTP\Response.

Not sure what you mean by this, as HTTP\Response extends HTTP\Message.

> Only variables should be passed by reference // ->setBody(json_encode($json));

This isn't the setBody method having an issue, since the setBody method is used elsewhere in the framework to actually output the final views. So it does work. The problem, I believe, lies in trying to use json_encode within the setBody method. Move that out of the argument spot and it should work just fine: 

```
$json = json_encode($json);
$this->response->setStatusCode(200)
	               ->setBody($json);
```
