### ISSUE TITLE
Writable directory question

### ISSUE THREAD

**Issue by kirill-mally** [bcit-ci/CodeIgniter4#407]
Hi,
I'm sorry if I asked not in correct branch or project.

My question is about work with /writable directory.
Totally like the approach of setting index.php into separate folder and dividing writable files as separate.
But when I tried to recreate the workflow for myself, I faced the problem, that whenever I put for example:
- /writable/minified - stylesheets and scripts that are dynamically minified and written during the load.
- /writable/uploads/avatar.gif - dummy image file for test.

How can I access them from frontend side, for example in header, while loading stylesheets:
`<link rel='stylesheet' type='text/css' href='[domain]/writable/minified/core.min.css'>`
And I understand that by logic you simply can't access secured and outer directory. Then how to get the content of the file by link? Through some specific helper and read of file?

Or for e.g. for load of image:
`<img class="preloader-logo" src="[domain]/writable/uploads/avatar.gif" />`
anywhere on the frontend etc.

Thank you for information and really hope you will not delete question or can answer me directly. I'm confused about this one.

**Comment by jim-parry** [comment]
Support questions should be posted on our [forum](https://forum.codeigniter.com/forum-30.html)
Rather than close your "issue" immediately, I can point out that only folders/files underneath "public" are intended to be browser accessible. The writable folder isn't.
You could modify application/Config/Paths.php, and specify a folder inside public, but you would then have to be careful not to store anything sensitive there.
Now I can close this "issue".
