### ISSUE TITLE
Call to a member function getResult() on boolean

### ISSUE THREAD

**Issue by krecebli** [bcit-ci/CodeIgniter4#409]
any find* method of model class throws this error:
![screenshot from 2017-02-17 17-42-46](https://cloud.githubusercontent.com/assets/13809906/23067404/980d8a8c-f538-11e6-86a2-2f1af6774aae.png)

i "played" a little in BASEPATH/Model.php file, and found that dumping `$builder->where($this->primaryKey, $id)->get()` (for example) works fine, `var_dump` dumps it as it should, the line `$builder->where($this->primaryKey, $id)->get()` is assigned to `$row` variable,  but `vard_dump($row)` dumps `false`, so the next line `$row = $row->getFirstRow($this->tempReturnType)` throws an error "Call to a member function getResult() on boolean"

**Comment by lonnieezell** [comment]
Hm. Not able to replicate this. Using the latest version of develop, I used the following code in a controller: 

```
$model = new class() extends Model {
	        protected $table = 'job';
        };

	    $results = $model->findAll();

	    $developer = $model->findWhere('name', 'Developer');

	    $politician = $model->find(3);
```

This is using the database setup from the test data, but all three vars ($results, $developer, and $politician) bring back the correct data successfully. This is using MySQL. 

Can you confirm that your database is setup and you can access it through the build directly or with a raw query? Also, what database are you using, Postgre?

I'm a little surprised you're running into this, honestly, since the [live database tests on Travis](https://travis-ci.org/bcit-ci/CodeIgniter4) are all coming back successfull. Once we figure out what this is, sounds like we need a better error report of what's actually happening here.

**Comment by krecebli** [comment]
yes, my db is setup and it works as should with ci3, my db is mysql, when i use query builder:
```php
$db = \Config\Database::connect();
$builder = $db->table('table');
$query = $builder->get();
```
...everything works perfectly, but when i try to using anything from this guide `https://bcit-ci.github.io/CodeIgniter4/database/model.html` and from the pagination guide, got the error i described in post

but... i have tried your code example and again got that error on the $politician, the first and second bring back the correct data successfully

**Comment by lonnieezell** [comment]
Sorry, I completely dropped the ball on this one. 

Did you ever figure out what was going on? If not, can you: 

- verify that the data you're trying to pull from my previous examples does exist in your database with the correct ID (3) for politician, or at least that a row exists there.
- Show your database config settings

**Comment by rudrak23** [comment]
Got this and not able to figure out how to solve it.

My model code:
```
$query = $builder->get();
return $query->getResultArray();        //Call to a member function getResult() on boolean on this line
```

**Comment by kenjis** [comment]
@rudrak23 
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
