### ISSUE TITLE
API Response Trait :: failValidationError() Status Code 422

### ISSUE THREAD

**Issue by natanfelles** [bcit-ci/CodeIgniter4#420]
Hello!

I am studying the new documentation and that the `failValidationError()` method of the *API Response Trait* library responds to code 400 by default.

I'm not sure, but I just see how to answer the code validation errors at http://doers.statuspage.io/api/v1/users/ and http://stackoverflow.com/questions/16133923/400-Vs-422-response-to-post-of-date as 422.

I wonder if this can be changed in the default system.

Thank you. CI 4 is incredible.

**Comment by lonnieezell** [comment]
The SO link you provided has much more concrete arguments for using 400 than StatusPage using a 422. By default, I think it should stay a 400, since that link is very much inline with much of the reading up on it that I had done previously. If a developer wishes to use a different value, they can always customize it for their needs.
