### ISSUE TITLE
CLI new commands 

### ISSUE THREAD

**Issue by baselbj** [bcit-ci/CodeIgniter4#433]
Hi;

I can see that CLI needs more functions mainly the following will be a grate additions:

app
  app:name               Set the application namespace ... I am not sure about this if it is applicable
create
  create:module          Create a new module (namespace folder)as the standers in Code Modules
  create:command      Create a new CLI command class
  create:controller       Create a new controller class   
  create:model            Create a new model class where it will ask for  $table and $primaryKey
  create:seeder           Create a new seeder class
  create:test                Create a new test class 
  create:DBtest           Create a new database test class
  create:mail               Create a new email class ... This can be added later as that email class in progress
  create:module         Create a new module (namespace folder)as the standers in Code Modules.

**The create:module CLI command:**

this command will help in creating a new module folder this will include:
1- create module folder in specific folder.
2- might update psr4 in auto-loading, if possible.
2- create (MVC) folders with default welcome files with correct namespace.
 
If this is agreed I can start with that and if you have any other commands that can be added please tell me.

Regards;

**Comment by lonnieezell** [comment]
Unfortunately, at this time the project team doesn't want to have code generators in the base. I've violated that a touch with the create a migration since I've always thought the timestamp was a pain to do manually. 

However, I've started a side project, called [vulcan](https://github.com/lonnieezell/vulcan) to implement these types of tools for CI that I hope will become an official tool at some point, since there was talk of having something like this optional. If you want to help out with that I'd welcome the help, since it's a little on the back-burner right now as I try to make progress with CI4.

**Comment by baselbj** [comment]
I will be glad helping as I am free now

**Comment by baselbj** [comment]
anyway I fee it is weird not to accept such functionality as it will not affect the performance. I totally agreed with not having an authentication module but this can be so much helpful.

**Comment by lonnieezell** [comment]
All I can say is that I happen to agree with you, but that's not what we're going to be doing currently, unfortunately.
