### ISSUE TITLE
Validation Rule Constants

### ISSUE THREAD

**Issue by EpicKris** [bcit-ci/CodeIgniter4#436]
This might just be me being clumsy, but I've had a few instances of incorrectly setting validation rules (typos, etc…), what about having rule constant strings?

For example:
``` php
class Rules
{
    const REQUIRED = 'required';
    const IS_NATURAL_NO_ZERO = 'is_natural_no_zero';
}

$rules = [
    'id' => implode('|', [Rules::REQUIRED, RULES::IS_NATURAL_NO_ZERO])
];
```

Could even add a convenience method to the validation class:
``` php
class Validation
{
    public static function concatRules(string ...$rules): string
    {
        return implode('|', $rules);
    }
}

$rules = [
    'id' => Validation::concatRules([Rules::REQUIRED, Rules::IS_NATURAL_NO_ZERO])
];
```

**Comment by lonnieezell** [comment]
I'm not convinced of this one, @EpicKris. The only benefit is that the IDE could do autocomplete. I'm afraid, though, that if we add this due to the error-prone word `required` (and yes, I misspell it too often myself), then we will have to start creating a lot of special case rules like this. 

So, sorry, not this one.
