### ISSUE TITLE
Couldn't manage without index.php

### ISSUE THREAD

**Issue by MarlonJD** [bcit-ci/CodeIgniter4#541]
I'm using CI3 without index.php suffix but I couldn't manage this link style like sitename.com/controller-name/function . How can I do this in CI4. I couldn't found working reply. If this topic is forbidden or something like that. please inform me.

**Comment by InsiteFX** [comment]
This is for CI 4 not CI 3, You need to go to the CI 3 Issues...

**Comment by MarlonJD** [comment]
No. issue in on CI4. İ mean i cannot found solution for this issue for ci4.

**Comment by timothymarois** [comment]
@MarlonJD Are you using apache and .htaccess for the mod_rewrite? By default CI4 is designed for that link style already. `example.com/controller/method`, but that is of course depending on your routing settings. But I dont know your setup, by default CI4 shouldn't require index.php to be within the url structure.

**Comment by MarlonJD** [comment]
Yes there is CI3 projects on my local lamp stack and these are working. But in CI4 i can only access like http://localhost/public/index.php/home otherwise localhost/public/home is not working.

**Comment by timothymarois** [comment]
Side note, You need to point your domain to the `/public` directory, that is a change with CI4 as well. This way public is not in the address of the website. What do you get when trying to access `localhost/public/home` ?

**Comment by MarlonJD** [comment]
Actually i'm trying to access controller but without public it's not working. So how can i do this in locally, with htaccess?

**Comment by timothymarois** [comment]
Are you using apache on your local machine?

**Comment by MarlonJD** [comment]
Yes im using apache on arch linux

**Comment by timothymarois** [comment]
And you have `/public/.htaccess` ?

**Comment by MarlonJD** [comment]
Yes there is

**Comment by jim-parry** [comment]
Move this to the forum, please. We use github for bug tracking and approved work packages.
Configure your virtul hist or aache so that the *public* folder in your project is the document root. See the repo readme!

**Comment by timothymarois** [comment]
@MarlonJD - I'll just drop one last note here. Inside `application/config/App.php` you can set `public $indexPage = 'index.php'` to blank `public $indexPage = '';` I usually don't change this, but if using mod_rewrite you can set this to blank so that it doesn't use this within the url structure, though I'm unsure how your app is configured. Just be sure apache mod_rewrite is enabled, and follow the CI 4 docs for more information. And yes, this issue should be dealt with using the forums or even stackoverflow for more feedback.  https://bcit-ci.github.io/CodeIgniter4/
