### ISSUE TITLE
CodeIgniter\Files\File() and FileNotFoundException issue with creating new files

### ISSUE THREAD

**Issue by timothymarois** [bcit-ci/CodeIgniter4#548]
I'm adding this as an issue because you're unable to create a file using the file class. It automatically hits `FileNotFoundException` when the file does not exist, and preventing `$file->openFile('w')` from allowing it to create the file. 

As for documentation: [Getting a File instance](https://bcit-ci.github.io/CodeIgniter4/libraries/files.html?highlight=file#getting-a-file-instance)

> The file does not need to exist.

Technically it will need to exist, because without using a `try/catch` the application will crash. Forcing you to use the default `fopen` if you need to create the file on the fly.

**Comment by lonnieezell** [comment]
Ah. Looks like docs may be off there, since you can bypass the exception by passing `false` as the second parameter in the constructor: 

```
$file = new File($path, false);
```

I'm guessing I originally meant it to be default to false... and then forgot to change docs when it was changed. Most likely while I was working on the Image library.

see: https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Files/File.php#L61

**Comment by timothymarois** [comment]
ah I see. cool. no worries then.
