### ISSUE TITLE
$session->destroy() and $session->stop() do not work?

### ISSUE THREAD

**Issue by donpwinston** [bcit-ci/CodeIgniter4#592]
I had to use session_destroy() which did work.

**Comment by lonnieezell** [comment]
Need more details. How did you start the session. Which driver were you using? etc... 

Though it's possible just looking at the `stop()` function that it's missing a crucial piece. Still need the details to debug properly for you, though.

**Comment by satchwinston** [comment]
In my controller's constructor I have the following:
$this->session = \Config\Services::session();
$this->session->start();

I'm using the file system. 
I've numerous routes that add to the session and
I've a route that simply clears the session and redirects to a page:

public function clear()
{
    $this->session->stop();
    //redirect('/register');
    print "<pre>"; print_r($this->session->get()); print "</pre>";
}

**Comment by lonnieezell** [comment]
Ok, cool. Just making sure you weren't calling PHP's `session_start` anywhere, because that would screw things up. 

I'll be honest, I'm familiar with the internals of the Session libs too much, I just ported over what CI3 had since it had just been rewritten by Narf. However, looking through the code here's what happens: 

- sets the session cookie to an empty value
- regenerates the session_id so that the session is no longer in use
- in the FileHandler for this session, in the `close()` method, it releases the file lock and forgets all info about that. 

Looking at [the custom session handler docs](http://php.net/manual/en/session.customhandler.php) the session is not completely destroyed until you specifically call it. In your example I believe the $_SESSION global would still be around, but no data would be in it anymore. It was never destroyed. Additionally, as long as the session classes have been loaded, the functions will be available to call. 

What you didn't mention was whether the data was still around or not. It shouldn't be based on what I've seen in the code.

**Comment by satchwinston** [comment]
The data appears to still be there unless I call session_destroy() instead of $this->session->stop().

**Comment by lonnieezell** [comment]
That is the behavior I would expect based on those docs I linked to before. Sounds like it's all working as it should, then.

**Comment by Crenel** [comment]
I don't understand how leaving data intact after $session->stop() is correct functionality (i.e., "working as it should"). The CI 4 documentation clearly states that stop() can be used to destroy a session, but this is not happening. I don't know how long this may have been the case, but it's definitely true in 4.3.4. If I replace PHP's session_destroy() with CI4's $session>stop(), nothing happens to the session, all of the data remains - in my case, leaving me logged in despite attempting to log out. This represents a serious security risk.

**Comment by kenjis** [comment]
Don't use `$session->stop()` now. It seems broken.
It seem to be a bug.

**Comment by ahmetboz** [comment]
Is there any solution about that?

**Comment by Crenel** [comment]
This issue needs to be reopened (which I can't do), or a new one should be created that maybe references this one (which I'm not sure how to do).

"Just don't use it" is not a sufficient answer - this is a serious security flaw that will affect anyone who doesn't stumble across that bit of (critical!) advice.

If this github issue is any indication, this gaping hole has existed for years without anybody taking it seriously. That alone makes me question whether I should just abandon CodeIgniter (right when I was trying to build new systems on it). If the framework contributors are so disjointed that there is no cohesive team sense, or if there is a cohesive project team but they can't or won't recognize a major security flaw and fix it promptly, it's a lost cause.

Please... somebody... if there is someone / some team to which a severe security flaw can be escalated, get their eyes on this issue immediately.

**Comment by ahmetboz** [comment]
> Is there any solution about that?

I've solved with `session_destroy();` temporarily.

**Comment by donpwinston** [comment]
I have no idea why there is a start and stop protocol to begin with. I'm sure almost no one uses it. All anyone needs is to create the session and destroy it.

**Comment by lonnieezell** [comment]
I opened a new issue to update the docs, #7501

**Comment by Crenel** [comment]
Making this a documentation-only change leaves vulnerable any site built with the untested assumption that stop() will (for example) log somebody out (which it demonstrably does not do). So, either stop() needs to be deleted or renamed (intentionally breaking backward compatibility to "aggressively suggest" the use of session_destroy()), or it's purpose _and functionality_ need to match the original documented purpose.

**Comment by kenjis** [comment]
@Crenel See #7503
We will merge it soon. If you have opinion, comment in the PR.
