### ISSUE TITLE
Image resizing issue

### ISSUE THREAD

**Issue by chistel** [bcit-ci/CodeIgniter4#610]
attempting to use the image library to resize, i get response "imageProcessFailed"
bu
below is the code used.

`if ($file = $this->request->getFile('event_image'))
			        	{
			        		if ($file->isValid() && ! $file->hasMoved())
							{
								$path = FCPATH.'static/eventimg';
			            	$filename = 'event_image-' .$file->getRandomName();
			            	$file_full_path = $path . '/' . $filename;
							   $file->move($path, $filename);

								$image = \Config\Services::image('imagick')
								        ->withFile($file_full_path)
								        	->resize(800, 300, true)
								        ->save(FCPATH.'static/eventimg/small/mypic_thumb.jpg');
								
			        	}`

**Comment by InsiteFX** [comment]
You have a single quote before the first if statement is that a mistake?

**Comment by lonnieezell** [comment]
That error happens when attempting to call ImageMagick using the `exec` function [here](https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Images/Handlers/ImageMagickHandler.php#L196). This could be any number of things. Checking your system's error records is the best thing to do. These other steps could help:

1. Verify the path to ImageMagick's **convert** command is set correctly in `application/Config/Images`.
2. Check the server error logs
3. Ensure `exec` is enabled on your server.

**Comment by chistel** [comment]
yea I figure that out, using Gd handler in main time pending when I get it fixes from my end
