### ISSUE TITLE
Add support for foreign keys to the Forge

### ISSUE THREAD

**Issue by lonnieezell** [bcit-ci/CodeIgniter4#63]
Development Checklist:
- [ ] Component(s)
- [ ] ... with PHPdocs
- [ ] Unit testing
- [ ] ... with >80% coverage
- [ ] User guide updated
- [ ] Classmap integration?
- [ ] Securely signed commits
- [ ] Conforms to style guide

**Comment by davidgv88** [comment]
Pull Request #252

**Comment by timothymarois** [comment]
@lonnieezell  I've begun working on this and functions properly with MySQL, adding foreign keys, and retrieving foreign keys on selected tables. However I'm not able to get it working with postgre yet. I've taken @Portaflex original code as a jump start, with adding new additions such as retrieval of the foreign keys on a table, since that will be important in knowing if one exist, its name and their keys etc. With postgre need the retrieval of the foreign keys. Adding foreign keys looked similar in sql. But will need more testing.

**Comment by lonnieezell** [comment]
@timothymarois Sounds great, thanks!
