### ISSUE TITLE
Entity exception in line 270 and 143 (current version).

### ISSUE THREAD

**Issue by nowackipawel** [bcit-ci/CodeIgniter4#780]
array_key_exists is not as perfect as we'd like to be :).  So after updating my repo my project stopped working. 
I think will be better at least to use:

system/Entity.php->mapProperty() : 270
`if (!empty($this->_options['datamap']) && ( isset($this->_options['datamap'][$key]) || array_key_exists($key, $this->_options['datamap'])) )`

and:
system/Entity.php->__get() : 147
`else if (!empty($this->_options['casts']) && ( isset($this->_options['casts'][$key]) || array_key_exists($key, $this->_options['casts'])) )`

instead of:

`if (array_key_exists($key, $this->_options['datamap']))`

and

`else if (array_key_exists($key, $this->_options['casts']))`

Anyway widely used in_array is not perfect as well.

/** Edited for previous backward compabillity ;-) **/

**Comment by lonnieezell** [comment]
I know this is really late - and I apologize. I've been overloaded for a while. 

You didn't state what problems you were encountering, but I think you're right. I typically prefer `array_key_exists` since it doesn't do any value check, but in this case the value check is fine. I'm switching them to use `isset` and `! empty`. 

Thanks.
