### ISSUE TITLE
View Parser escaping data even if passed 'raw' as context in setData()

### ISSUE THREAD

**Issue by gustavojm** [bcit-ci/CodeIgniter4#788]
I expected that if setData was called with 'raw' as context the data won't be escaped at all, but replaceSingle is called with $escape=TRUE which ends up using esc(html) to escape the data.
I know that using {!  !} will force the parser not to escape the data, but I expected the same result with setData and 'raw' context.
Is this the right behaviour?

**Comment by lonnieezell** [comment]
That's a good point. I need update the docs to point that out. I'm trying to think of a way to make the two work together but can't currently think of one, so they will have to stay independent for now. 
I'm going to leave this open for now, though, to remember to check this out some more, since I'm not in front of the code right now. Also makes me realize I need to check and ensure things aren't getting escaped twice... which I'm pretty sure was account for, but would be a good check.
