### ISSUE TITLE
Bug toolbar

### ISSUE THREAD

**Issue by deathart** [bcit-ci/CodeIgniter4#834]
Hello,

Following the change felt on the debug toolbar, the javascript side no longer works.
I started by checking if there were any JS errors on the console, but no errors!
I then tried to put back 

```js
    <script>
        ciDebugBar.init();
    </script>
```

At the end of the file "tootbar. tpl. php" and everything works again!
Knowing that I have the last commit!
So the problem is me? or is this piece of code really missing?

Sorry for my English.

**Comment by lonnieezell** [comment]
I'll try to look into that tonight. I know that it works on a default CI4 install. However, I did notice late last night that it didn't work on one of my test sites, but hadn't had a chance to determine why, yet. That gives me something to look into though, if no one else fixes it before I can :)

Thanks!

**Comment by lonnieezell** [comment]
Figured out why - since you've got a test application I'm assuming your application/Config folders were not being updated, just the system directory. There are a couple of big changes to the way the toolbar works that require you do a couple of things in your application folder to migrate to the latest change: 

1. Add the following line to **application/Config/Events.php**, just under the Database one: 

```
Events::on('pre_system', 'CodeIgniter\Debug\Toolbar::eventHandler');
```

2. Replace the contents of the existing Toolbar filter (**application/Filters/DebugToolbar.php**) with the one in the [current version](https://github.com/bcit-ci/CodeIgniter4/blob/develop/application/Filters/DebugToolbar.php).

Then you should be good to go.

**Comment by deathart** [comment]
Yes, I forgot to update the https://github.com/bcit-ci/CodeIgniter4/blob/develop/application/Filters/DebugToolbar.php file.
Sorry :D

**Comment by deathart** [comment]
But now the rest of my JS code doesn't work anymore because of
**id="debugbar_loader"** in the code: 
```js
$script = PHP_EOL
                . '<script type="text/javascript" id="debugbar_loader" '
                . 'data-time="' . $time . '" '
                . 'src="' . rtrim(site_url(), '/') . '/?debugbar"></script>'
                . PHP_EOL;
```

**Comment by lonnieezell** [comment]
What problems are you seeing because of that? From what I understand an "id" attribute is valid on all html5 pages. Are you seeing issues validating against HTML4?

**Comment by natanfelles** [comment]
Well, I having am issue related here. The toolbar is not loading in two ways:

#### 1 - /
Accessing http://localhost:8080 the toolbar do not appears. I followed the script url `http://localhost:8080/index.php?debugbar` and see that this page has the same html of the welcome_message.php view. 

To solve this and load the js page I removed the [rtrim()](https://github.com/bcit-ci/CodeIgniter4/blob/6c175688c7f51f95a621de7b9dc98b90c4201479/application/Filters/DebugToolbar.php#L67) to just `. 'src="' . site_url() . '?debugbar"></script>'`.

The toolbarloader also was not loading the toolbar html, then removing [other rtrim()](https://github.com/bcit-ci/CodeIgniter4/blob/6c175688c7f51f95a621de7b9dc98b90c4201479/system/Debug/Toolbar/toolbarloader.js.php#L6) to just `var url = "<?= site_url() ?>";` the toolbar back to be showed.

My doubt is why to use the *rtrim()*?

Without the / after index.php the http get method is not working here.

#### 2 - /index.php

Also if I access http://localhost:8080/index.php the toolbar do not appears and this occurs for some strange reason that the `$_SERVER['CI_ENVIRONMENT'] = 'development';` of the *rewrite.php* is not being declared. Of course, I do not understand, yet, why this is being ignored.

Yes, I am running the `php serve` CLI.

---

Had you some issue related or is it occurring only with me? If it is a general issue, I believe that the rtrim()'s is not necessary, to begin...

**Comment by gustavojm** [comment]
Both rtrim were put because if $indexPage = index.php in App.php the toolbar would be loaded from
index.php/?debugbar generating a HTTP 301 redirect.
After the redirect the toolbar worked, but it created an unnecessary request.
Please check the network tab of the developper tools on the browser to see if the redirects happen without the rtrim. 
Maybe it's just my rewrite config in .htaccess that causes it.
I'm on holidays so unaware of investigating this issue further.

**Comment by natanfelles** [comment]
Hi, @gustavojm . Good evening.

Not redirect here:

![captura de tela de 2017-11-18 21-16-37](https://user-images.githubusercontent.com/3011423/32985588-d53d7bca-cca5-11e7-8a42-d7a05aae017c.png)

**Comment by gustavojm** [comment]
Thanks @natanfelles I guess that the rtrims can be removed then, and I'll try to figure out what's wrong in my setup. If you can, create the PR.
Sorry for that!

**Comment by deathart** [comment]
So my pages are in html5, but the problem is that because of this id="debugbar_loader" the rest of my JS scripts don't work anymore.

On the other hand, the debug toolbar works without worries.

And my problem has nothing to do with rtrims, because with or without it there is no difference.

**Comment by natanfelles** [comment]
Here has difference:

![captura de tela de 2017-11-19 18-27-32](https://user-images.githubusercontent.com/3011423/32995128-6923a7ae-cd57-11e7-87b2-8fde5c68cdc6.png)

Look that the xhr is not loaded. It occurs because the `index.php?debugbar` is returning the html view.

Of course this could not have difference with or without a `/`.

---

@deathart Is the  id `debugbar_loader` being duplicated? What your console show about your javascript code? Is your javascript really being loaded?

**Comment by deathart** [comment]
So no it's not duplicating, I have no info in the console logs and yes all this load correctly it's for that I don't understand at all.

**Comment by puschie286** [comment]
hey, same problem here. some js interactions doesnt work anymore ( onclick still get triggered )

tested on all browsers ( firefox, chrome, edge ) with same result, so guess its no js implementation bug
@deathart  i use just ci and have the same problem

i will have a closer look tomorrow

**Comment by deathart** [comment]
I confirm that https://github.com/bcit-ci/CodeIgniter4/pull/843/files solves my problem.

**Comment by natanfelles** [comment]
@deathart if you want, you can close this issue. My "related issue" is solved too. :)
