### ISSUE TITLE
validation form_error()

### ISSUE THREAD

**Issue by catwithredhat** [bcit-ci/CodeIgniter4#911]
Why theres no helper form_error() like ci3?

https://bcit-ci.github.io/CodeIgniter4/helpers/form_helper.html

The doc describe abt form_error 
But theres no function form_error

https://github.com/bcit-ci/CodeIgniter4/blob/develop/system/Helpers/form_helper.php

**Comment by lonnieezell** [comment]
You are correct, `form_error` no longer exists. This is because validation was separated from the form to make it more flexible. The fact that it still exists in the docs is an artifact of porting the docs over from CI3. 

See the [Validation](https://bcit-ci.github.io/CodeIgniter4/libraries/validation.html#getting-all-errors) docs for a (hopefully) up to date explanation.

**Comment by akrindev** [comment]
so sad heard dat the form_error helper is removed on ci4, it is very helpful

**Comment by lonnieezell** [comment]
@akrindev It's not needed. use `session()` and it's  just as simple: 

In controller:
```
if (! $this->validate($rules))
{
    return redirect()->back()->withInput()->with('errors', $userModel->errors());
}
```
In view: 
```
<div class="invalid-feedback">
    <?= session('errors.pass_confirm') ?>
</div>
```
