### ISSUE TITLE
IncomingRequest getUserAgent problem only object

### ISSUE THREAD

**Issue by byazrail** [bcit-ci/CodeIgniter4#948]
Hi guys,

`
public function getUserAgent($onlyObject = false)
{
	return ($onlyObject === true) ? $this->userAgent : $this->userAgent->getAgentString();
}
`

**Comment by lonnieezell** [comment]
I'm assuming this is a proposal? An explanation to go along with the comment is always good so I don't have to go attempting to decipher your intent. :)

Actually - the intent was to add a _toString so that you could echo it out, and it looks like I forgot that. That would be the solution I'd accept.

**Comment by byazrail** [comment]
Yes __toString correct solution :)
